export const RESERVATIONS_SET_LOADING = 'RESERVATIONS_SET_LOADING';
export const RESERVATIONS_UNSET_LOADING = 'RESERVATIONS_UNSET_LOADING';
export const RESERVATIONS_SET_RESERVATIONS  = 'RESERVATIONS_SET_RESERVATIONS';