export const INTERACTIVE_TABLE_SET_LOADING = 'INTERACTIVE_TABLE_SET_LOADING';
export const INTERACTIVE_TABLE_UNSET_LOADING = 'INTERACTIVE_TABLE_UNSET_LOADING'
export const INTERACTIVE_TABLE_SET_SEARCH_COLUMN = 'INTERACTIVE_TABLE_SET_SEARCH_COLUMN'
export const INTERACTIVE_TABLE_SET_SEARCH_VALUE = 'INTERACTIVE_TABLE_SET_SEARCH_VALUE';
// export const INTERACTIVE_TABLE_SET_CURRENT_TABLE = 'INTERACTIVE_TABLE_SET_CURRENT_TABLE';