export const AUTH_OPEN_DIALOG = 'AUTH_OPEN_DIALOG';
export const AUTH_CLOSE_DIALOG = 'AUTH_CLOSE_DIALOG';
export const AUTH_SET_REGISTRATION = 'AUTH_SET_REGISTRATION';
export const AUTH_SET_LOGIN = 'AUTH_SET_LOGIN';
export const AUTH_SET_LOGIN_MESSAGE = 'AUTH_SET_LOGIN_MESSAGE';