export const EMPLOYEES_SET_LOADING = 'EMPLOYEES_SET_LOADING';
export const EMPLOYEES_UNSET_LOADING = 'EMPLOYEES_UNSET_LOADING';
export const EMPLOYEES_SET_EMPLOYEES  = 'EMPLOYEES_SET_EMPLOYEES';
export const EMPLOYEES_SET_SCHEDULE  = 'EMPLOYEES_SET_EMPLOYEES';
export const EMPLOYEES_SET_EDIT = 'EMPLOYEES_SET_EDIT';