export const AVAILABILITY_SET_HOTELS = 'AVAILABILITY_SET_HOTELS';
export const AVAILABILITY_SET_ROOM_TYPES = 'AVAILABILITY_SET_ROOM_TYPES';
export const AVAILABILITY_SET_ROOM_TYPE = 'AVAILABILITY_SET_ROOM_TYPE';
export const AVAILABILITY_SET_PARAMS = 'AVAILABILITY_SET_PARAMS';
export const AVAILABILITY_UNSET_ROOM_TYPE = 'AVAILABILITY_UNSET_ROOM_TYPE';
export const AVAILABILITY_SET_CITIES = 'AVAILABILITY_SET_CITIES';