export const ADMIN_TABLE_SET_LOADING = 'ADMIN_TABLE_SET_LOADING';
export const ADMIN_TABLE_UNSET_LOADING = 'ADMIN_TABLE_UNSET_LOADING'
export const ADMIN_TABLE_SET_SEARCH_COLUMN = 'ADMIN_TABLE_SET_SEARCH_COLUMN'
export const ADMIN_TABLE_SET_SEARCH_VALUE = 'ADMIN_TABLE_SER_SEARCH_VALUE';