export const ALL_RESERVATIONS_SET_RESERVATIONS = 'ALL_RESERVATIONS_SET_RESERVATIONS';
export const ALL_RESERVATIONS_SET_LOADING = 'ALL_RESERVATIONS_SET_LOADING';
export const ALL_RESERVATIONS_UNSET_LOADING = 'ALL_RESERVATIONS_UNSET_LOADING';

