export const ALL_RESERVATIONS_SET_RESERVATIONS = 'ALL_RESERVATIONS_SET_RESERVATIONS';
export const ALL_RESERVATIONS_SET_LOADING = 'ALL_RESERVATIONS_SET_LOADING';
export const ALL_RESERVATIONS_UNSET_LOADING = 'ALL_RESERVATIONS_UNSET_LOADING';
export const ALL_RESERVATIONS_SET_EDITING = 'ALL_RESERVATIONS_SET_EDITING';
export const ALL_RESERVATIONS_UNSET_EDITING = 'ALL_RESERVATIONS_UNSET_EDITING';
export const ALL_RESERVATIONS_SET_DELETE = 'ALL_RESERVATIONS_UNSET_DELETE';
export const ALL_RESERVATIONS_UNSET_DELETE = 'ALL_RESERVATIONS_UNSET_DELETE';
