export const READ_ALL_ORDERS = "READ_ALL_ORDERS";
export const WRITE_ALL_ORDERS = "WRITE_ALL_ORDERS";
export const WRITE_ALL_USERS = "WRITE_ALL_USERS";
export const READ_ALL_EMPLOYEES = "READ_ALL_EMPLOYEES";
export const READ_ALL_SCHEDULES = "READ_ALL_SCHEDULES";
export const WRITE_ALL_SCHEDULES = "WRITE_ALL_SCHEDULES";

export const READ_ALL_SEASONAL_RATES = "READ_ALL_SEASONAL_RATES";