export const READ_ALL_ORDERS = "READ_ALL_ORDERS";
export const WRITE_ALL_ORDERS = "READ_ALL_ORDERS";
export const WRITE_ALL_USERS = "READ_ALL_ORDERS";
export const READ_ALL_EMPLOYEES = "READ_ALL_ORDERS";
export const READ_ALL_SCHEDULES = "READ_ALL_ORDERS";
export const WRITE_ALL_SCHEDULES = "READ_ALL_ORDERS";